{
 "title": "OS General",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Общая информация", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Объем свободного места",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$node\", fstype!~\"tmpfs|overlay\", mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество файловых дескрипторов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Принятый/Отправленный трафик",
   "type": "timeseries",
   "description": "Per-interface network traffic (receive and transmit) in bits per second",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(node_network_receive_bytes_total{\n    instance=\"$node\",\n    job=\"$job\",\n    device=~\"eth.*|en.*|bond.*\"\n  }[$__rate_interval])\n) * 8",
     "legendFormat": "Принято {{device}}"
    },
    {
     "expr": "sum(\n  rate(node_network_transmit_bytes_total{\n    instance=\"$node\",\n    job=\"$job\",\n    device=~\"eth.*|en.*|bond.*\"\n  }[$__rate_interval])\n) * 8",
     "legendFormat": "Отправлено {{device}} "
    }
   ]
  }
 ]
}